/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1_1_2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testToString() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        assertEquals("x^3 + 2x^2 + 1", p1.toString());

        Polynomial p2 = new Polynomial(new int[] {0, 0, 0});
        assertEquals("0", p2.toString());
    }

    @Test
    public void testPlus() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        Polynomial p2 = new Polynomial(new int[] {-3, -2, 0, 1});

        Polynomial result = p1.plus(p2);
        assertEquals("-2x^3 + 2", result.toString());
    }

    @Test
    public void testMinus() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        Polynomial p2 = new Polynomial(new int[] {-3, -2, 0, 2});

        Polynomial result = p1.minus(p2);
        assertEquals("4x^3 + 4x^2 - 1", result.toString());
    }

    @Test
    public void testEquals() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        Polynomial p2 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        Polynomial p3 = new Polynomial(new int[] {-3, -2, 0, 1});

        assertTrue(p1.equals(p2));
        assertFalse(p1.equals(p3));
    }

    @Test
    public void testTimes() {
        Polynomial p1 = new Polynomial(new int[] {2, 1, 2});
        Polynomial p2 = new Polynomial(new int[] {-1, 2});

        Polynomial result = p1.times(p2);
        assertEquals("-2x^3 + 3x^2 + 4", result.toString());
    }

    @Test
    public void testDifferentiate() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        Polynomial result = p1.differentiate(1);

        assertEquals("3x^2 + 4x", result.toString());
    }

    @Test
    public void testEvaluate() {
        Polynomial p1 = new Polynomial(new int[] {0, 1, 2, 0, 1});
        long result = p1.evaluate(3);

        assertEquals(46, result);
    }
}

